name: Build React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      domain:
        description: 'Deployment domain'
        required: true
        default: 'smp-amberwoodrahatani.com'
      server_user:
        description: 'Server SSH username'
        required: true
        default: 'q2g3j98i4rdo'
      server_ip:
        description: 'Server IP'
        required: true
        default: '184.168.112.42'
      server_path:
        description: 'Target directory on server'
        required: true
        default: '/home/q2g3j98i4rdo/TEST/'
      server_pass:
        description: 'Server SSH password'
        required: true
        default: 'kkK8!PSJRUgX'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Export Inputs to Variables
        id: vars
        run: |
          echo "domain=${{ github.event.inputs.domain }}" >> $GITHUB_OUTPUT
          echo "user=${{ github.event.inputs.server_user }}" >> $GITHUB_OUTPUT
          echo "ip=${{ github.event.inputs.server_ip }}" >> $GITHUB_OUTPUT
          echo "path=${{ github.event.inputs.server_path }}" >> $GITHUB_OUTPUT
          echo "pass=${{ github.event.inputs.server_pass }}" >> $GITHUB_OUTPUT

      - name: Trigger SEO Generator
        run: curl https://${{ steps.vars.outputs.domain }}/seo-generator.php

      - name: Fetch seodata.json from server
        run: curl -o public/seodata.json https://${{ steps.vars.outputs.domain }}/seodata.json

      - name: Build React app
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Upload dist folder to server via rsync with password
        run: |
          sshpass -p "${{ steps.vars.outputs.pass }}" rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./dist/ ${{ steps.vars.outputs.user }}@${{ steps.vars.outputs.ip }}:${{ steps.vars.outputs.path }}

      - name: Trigger Sitemap generator
        run: curl https://${{ steps.vars.outputs.domain }}/sitemap-generator.php

      - name: Trigger .htaccess generator
        run: curl https://${{ steps.vars.outputs.domain }}/generate-htaccess.php
