name: Build React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 👈 This enables manual triggering from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    environment: PROD

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print SSH key (first 10 characters)
        run: echo "${{ secrets.SERVER_SSH_KEY }}" | head -c 10

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Fetch seodata.json from server
        run: curl -o public/seodata.json https://smp-amberwoodrahatani.com/seodata.json

      - name: Build React app
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Upload dist folder to server via rsync with password
        run: |
          sshpass -p "kkK8!PSJRUgX" rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./dist/ q2g3j98i4rdo@184.168.112.42:/home/q2g3j98i4rdo/TEST/
