name: Build React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      domain:
        description: 'Deployment domain'
        required: true
        default: 'smp-amberwoodrahatani.com'

jobs:
  build:
    runs-on: ubuntu-latest

    environment: PROD

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Determine Deployment Domain
        id: vars
        run: |
          if [ -z "${{ github.event.inputs.domain }}" ]; then
            echo "domain=smp-amberwoodrahatani.com" >> $GITHUB_OUTPUT
          else
            echo "domain=${{ github.event.inputs.domain }}" >> $GITHUB_OUTPUT
          fi

      - name: Trigger SEO Generator
        run: curl https://${{ steps.vars.outputs.domain }}/seo-generator.php

      - name: Fetch seodata.json from server
        run: curl -o public/seodata.json https://${{ steps.vars.outputs.domain }}/seodata.json

      - name: Build React app
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Upload dist folder to server via rsync with password
        run: |
          sshpass -p "kkK8!PSJRUgX" rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./dist/ q2g3j98i4rdo@184.168.112.42:/home/q2g3j98i4rdo/TEST/

      - name: Trigger Sitemap generator
        run: curl https://${{ steps.vars.outputs.domain }}/sitemap-generator.php

      - name: Trigger .htaccess generator
        run: curl https://${{ steps.vars.outputs.domain }}/generate-htaccess.php
